# This is a basic workflow to help you get started with Actions

name: Sync

# Controls when the workflow will run
on:
  # Triggers the workflow once per day at 12 am
  schedule:
  - cron: "0 14 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: test
        run: ls -R && pwd

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync Modules
        run: python util/cli.py sync

      - name: Git Commit Push Action
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          # Committer's email address
          email: ${{ github.actor }}@users.noreply.github.com
          # Committer's username
          name: ${{ github.actor }}
          # Commit message
          commit_message: Sync all modules
          # Branch to push the changes back to
          target_branch: ${{ github.ref }}
          # Files to add separated by space
          files: .
          # Repository url to push the code to
          remote_repository: origin
          # Token used to push the code
          access_token: ${{ github.token }}
