name: Sync Modules

on:
  schedule:
  - cron: "0 14 * * *"

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # update submodules
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      # cleanup
      - name: Clean local directory
        run: rm -f local/*

      # prepare pixelify zip
      - name: make pixelify zip
        run: zip -qq -r local/pixelify.zip Pixelify/module

      # prepare to build sui
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-module-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps

      - name: Cache Gradle Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-module-${{ github.sha }}
          restore-keys: |
            gradle-builds

      - name: Cache Ccache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-ccache-cache-

      - name: Install ccache
        working-directory: ./Sui
        run: |
          sudo apt-get install -y ccache
          ccache -o max_size=2G
          ccache -o hash_dir=false

      # build sui
      - name: Build sui-zygisk with Gradle
        working-directory: ./Sui
        run: |
          mkdir -p ~/.gradle/wrapper
          mkdir -p ~/.gradle/caches
          [ $(du -s ~/.gradle/wrapper | awk '{ print $1 }') -gt 250000 ] && rm -rf ~/.gradle/wrapper/* || true
          find ~/.gradle/caches -exec touch -d "2 days ago" {} + || true
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew zipZygiskRelease

      # move sui zip to local directory
      - name: move sui zip
        run: mv Sui/out/sui-zygisk-*-release.zip local/sui-zygisk.zip

      # prepare to sync with cli.py
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # sync with cli.py
      - name: Sync Modules
        run: python util/cli.py sync

      - name: Git Commit Push Action
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          # Committer's email address
          email: ${{ github.actor }}@users.noreply.github.com
          # Committer's username
          name: ${{ github.actor }}
          # Commit message
          commit_message: Synced and updated all modules
          # Branch to push the changes back to
          target_branch: ${{ github.ref }}
          # Files to add separated by space
          files: .
          # Repository url to push the code to
          remote_repository: origin
          # Token used to push the code
          access_token: ${{ github.token }}
