name: Sync Modules

on:
  schedule:
  - cron: "0 14 * * *"

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # update submodules
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      # cleanup
      - name: Clean local directory
        run: rm -f local/*

      - name: ??
        run: ls -R

      # prepare pixelify zip
      - name: make pixelify zip
        run: zip -qq -r local/pixelify.zip Pixelify/module

      # prepare to sync with cli.py
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # sync with cli.py
      - name: Sync Modules
        run: python util/cli.py sync

      - name: Git Commit Push Action
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          # Committer's email address
          email: ${{ github.actor }}@users.noreply.github.com
          # Committer's username
          name: ${{ github.actor }}
          # Commit message
          commit_message: Synced and updated all modules
          # Branch to push the changes back to
          target_branch: ${{ github.ref }}
          # Files to add separated by space
          files: .
          # Repository url to push the code to
          remote_repository: origin
          # Token used to push the code
          access_token: ${{ github.token }}
