name: Sync Modules

on:
  schedule:
  - cron: "0 14 * * *"

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # update submodules
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      # fetch zips that are stinky and annoying to get
      - name: fetch modules
        run: |
          # fetch v4a repackaged
          curl -s https://api.github.com/repos/programminghoch10/ViPER4AndroidRepackaged/releases/latest | jq -r ".assets[0] | .browser_download_url" | wget -O local/v4a.zip -i -
          # fetch sui
          curl -s https://api.github.com/repos/RikkaApps/Sui/releases/latest | jq -r ".assets[1] | .browser_download_url" | wget -O ./local/sui.zip -i -

      # sanity check idk
      - name: ??
        run: ls -R

      # prepare to sync with cli.py
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # sync with cli.py
      - name: Sync Modules
        run: python util/cli.py sync

      # commit changes
      - name: Git Commit Push Action
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          # Committer's email address
          email: ${{ github.actor }}@users.noreply.github.com
          # Committer's username
          name: ${{ github.actor }}
          # Commit message
          commit_message: Synced and updated all modules
          # Branch to push the changes back to
          target_branch: ${{ github.ref }}
          # Files to add separated by space
          files: .
          # Repository url to push the code to
          remote_repository: origin
          # Token used to push the code
          access_token: ${{ github.token }}
